[package]
name = "xena-UROP-2018"
version = "0.1"
lean_version = "master"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "12d103c2be5228087e61f02fb3414ca10b6dc69b"}
